### PR TITLE
Chef 17 Cleanup & Refactor

### LINKED ISSUE #5: Describe options usage in your README
It wasn't immediately obvious that I could pass options to the yum command. My install failed due to existing packages so I had to add --skip-broken to get it to work. My recipe:

```
yumgroup 'Server with GUI' do
  action :install
  options "--skip-broken"
end
```

### PR DESCRIPTION
**Pull request by detjensrobert**
# Description

This repo needed a bit of love to update it for the latest Chef versions and tooling.

Chef 17 requires resources to enable `unified_mode` in preparation for Chef 18, which is the main reason for the refactor.

## Changes included

- Refactor legacy LWRP to modern custom resource
- [Enable `unified_mode` for Chef 17 compatibility](https://docs.chef.io/deprecations_unified_mode/)
- Update testing to modern tooling / convention
  - Latest Cookstyle fixes  
  - Use InSpec instead of ServerSpec
  - Remove Foodcritic
  - Move spec tests to standard `spec/` location
  - Use new format ChefSpec tests
  - Add Kitchen Dokken testing (testing in Docker instead of Vagrant)
- Update README with proper documentation (fixes #5)

## Check List

- [x] All tests pass
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by detjensrobert** [comment]
Side note: if you would like to pass maintainer duties off, consider giving this cookbook to the [Sous Chefs](https://sous-chefs.org/)!

**Comment by mmmorris1975** [comment]
Honestly, I've been out of the Chef game since Chef 12.  If this works for you, I'm happy to accept this.  Thanks for the Sous Chefs tip, I'll look in to it!

**Comment by detjensrobert** [comment]
Can you please make a supermarket release with this change? :slightly_smiling_face:

**Comment by mmmorris1975** [comment]
Finally was able to dig out my supermarket credentials, and got this uploaded

**Comment by ghost** [comment]
@mmmorris1975 I only see version 0.7.0 on https://supermarket.chef.io/cookbooks/yumgroup. Should there be a 1.0.0? I ask because your [CHANGELOG](https://github.com/mmmorris1975/yumgroup/blob/master/CHANGELOG.md) doesn't match the actual releases. 

Also it appears core support for yum group installs has been abandoned per https://github.com/chef/chef/issues/2304 so you're still the official solution! Thanks again for this recipe!

**Pull request merged**
